#!/usr/bin/env node

global.fs = require('fs')
global.path = require('path')
global.chokidar = require('chokidar')
global.moment = require('moment')

global.print = console.log.bind(console)
String.prototype.repeat = function(v){return new Array(v+1).join(this)}
global.pad = function(v,s){return v+s.slice(v.length)}

//var minimist = require('minimist')
global.argv = {_:process.argv.slice(4)}

function File(file){this.path = file}
Object.defineProperty(File.prototype,'$',{get:function(){return this},set:function(v){if (v instanceof File) fs.createReadStream(v.path).pipe(fs.createWriteStream(this.path)); else fs.writeFileSync(this.path,v)}})
File.prototype.toString = function(){return fs.readFileSync(this.path)+''}
var t = function(file){return new File(file)}; t.__proto__ = fs; global.fs = t

// ------------------------------ //

if (process.argv[2]!=='core') print('oh dear, explosions!')
require(process.cwd()+'/'+process.argv[3].replace(/\.js$/,''))