package flea;

class e
{
	final int a = 4096;
	final int b = 16;
	final int c = 258;
	final int d = 23;
	final int e = 0;
	final int f = 1;
	final int g = 6;
	final int h = 50;
	final int i = 4;
	final int j = 18002;
	byte[] k;
	int l = 0;
	int m;
	int n;
	int o;
	byte[] p;
	int q = 0;
	int r;
	int s;
	int t;
	byte u;
	int v;
	boolean w;
	int x;
	int y;
	int z;
	int A;
	int B;
	int C;
	int D;
	int[] E = new int[256];
	int F;
	int[] G = new int[257];
	int[] H = new int[257];
	public static int[] I;
	int J;
	boolean[] K = new boolean[256];
	boolean[] L = new boolean[16];
	byte[] M = new byte[256];
	byte[] N = new byte[4096];
	int[] O = new int[16];
	byte[] P = new byte[this.j];
	byte[] Q = new byte[this.j];
	byte[][] R = new byte[6][258];
	int[][] S = new int[6][258];
	int[][] T = new int[6][258];
	int[][] U = new int[6][258];
	int[] V = new int[6];
	int W;
}